# Generated by Django 5.2.17 on 2026-08-17 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_pane_runtime_boot_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot_id', models.CharField(max_length=32, unique=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'battement runtime',
            },
        ),
        migrations.CreateModel(
            name='MCPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('pane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_alerts', to='workspaces.pane')),
            ],
            options={
                'verbose_name': 'alerte MCP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('active_panes', models.PositiveIntegerField(default=0)),
                ('max_panes', models.PositiveIntegerField(default=0)),
                ('cost_usd_today', models.FloatField(default=0.0)),
                ('turns_today', models.PositiveIntegerField(default=0)),
                ('external', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "instantané d'usage",
                'ordering': ['-taken_at'],
            },
        ),
    ]
