# Generated by Django 5.2.17 on 2026-09-17 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        ('workspaces', '0009_headless_default_opus_4_6'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(blank=True, help_text='Clé idempotente (seed)', max_length=120)),
                ('projet', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('telegram', 'Telegram (chat)'), ('cockpit', 'Cockpit (agents)'), ('veille', 'Veille éditoriale'), ('comms', 'Inbox / comms'), ('scraping', 'Scraping / prospection'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('conversations', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('resume', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['projet'], name='ops_session_projet_1df901_idx'), models.Index(fields=['source'], name='ops_session_source_2c2967_idx')],
            },
        ),
    ]
