# Generated by Django 5.2.17 on 2026-08-26 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasker', '0002_mission_planner_pane_alter_mission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('claude_bin', 'Binaire claude (abonnement)'), ('openai_http', 'Endpoint OpenAI-compatible (HTTP)')], max_length=16)),
                ('base_url', models.URLField(blank=True, help_text='openai_http uniquement — ex. http://192.168.1.20:8081/v1 (LAN/loopback seulement)')),
                ('model_id', models.CharField(blank=True, help_text='Id modèle côté endpoint ; vide pour claude_bin (défaut du binaire).', max_length=200)),
                ('context_window', models.PositiveIntegerField(default=32768)),
                ('max_tokens', models.PositiveIntegerField(default=4096)),
                ('supports_tools', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('healthy', models.BooleanField(default=False)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='MissionTokenBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_tokens', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('spent_prompt', models.PositiveIntegerField(default=0)),
                ('spent_completion', models.PositiveIntegerField(default=0)),
                ('policy_on_exhaust', models.CharField(choices=[('block', 'Bloquer'), ('degrade_to_local', 'Dégrader vers le local'), ('warn_only', 'Avertir seulement')], default='degrade_to_local', max_length=20)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_budget', to='tasker.mission')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('task_class', models.CharField(choices=[('draft', 'Draft / rédaction courte'), ('summarize', 'Résumé'), ('glue', 'Glue code / scripts'), ('route', 'Routage de messages'), ('code_small', 'Code borné'), ('code_heavy', 'Code lourd / refacto'), ('architecture', 'Architecture / conception'), ('long_context', 'Très long contexte'), ('default', 'Défaut')], default='default', max_length=32)),
                ('max_est_tokens', models.PositiveIntegerField(blank=True, help_text="Si l'estimation du prompt dépasse ce seuil, la règle ne matche pas.", null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='models_routing.modelbackend')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('task_class', models.CharField(default='default', max_length=32)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('error', 'error'), ('overflow', 'overflow'), ('budget_blocked', 'budget_blocked'), ('running', 'running')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('jsonl_path', models.CharField(blank=True, max_length=255)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='models_routing.modelbackend')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tasker.mission')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
