# Generated by Django 5.2.17 on 2026-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_tokens', models.PositiveIntegerField(default=7000000, help_text='Allocation totale de référence sur 7 jours.')),
                ('daily_cap_pct', models.DecimalField(decimal_places=2, default='14.30', help_text='Pourcentage max consommable par jour (14.3 % = 1/7).', max_digits=5)),
                ('note', models.CharField(blank=True, default='Pro Max 20x — €180/mois', max_length=200)),
            ],
            options={
                'verbose_name': 'budget global',
            },
        ),
        migrations.CreateModel(
            name='OpenclawExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='telegram', max_length=32)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('message_id', models.CharField(blank=True, max_length=40)),
                ('model_id', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log échange openclaw',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='models_rout_created_2e0e05_idx')],
            },
        ),
    ]
