# Generated by Django 5.2.17 on 2026-09-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('domaine', models.CharField(blank=True, max_length=200)),
                ('categorie', models.CharField(blank=True, help_text='slug de catégorie ; vide = principal', max_length=40)),
                ('is_principal', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('a_ouvrir', 'À ouvrir')], default='a_ouvrir', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_principal', 'categorie'],
            },
        ),
        migrations.CreateModel(
            name='PressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('expediteur', models.CharField(blank=True, max_length=200)),
                ('sujet', models.CharField(max_length=500)),
                ('recu_le', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('hotellerie', 'Hôtellerie & voyage'), ('design', 'Design & art de vivre'), ('mode', 'Mode & lifestyle'), ('food', 'Food & boissons'), ('culture', 'Art, culture & patrimoine'), ('archi', 'Architecture & BTP'), ('societe', 'Études & société'), ('salons', 'Salons & événements'), ('autre', 'Autre / à trier')], default='autre', max_length=40)),
                ('resume', models.TextField(blank=True)),
                ('corps', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('assigne', 'Assigné'), ('redige', 'Rédigé'), ('publie', 'Publié'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('blog_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='veille.blog')),
            ],
            options={
                'ordering': ['-recu_le', '-id'],
            },
        ),
    ]
