# Generated by Django 5.2.17 on 2026-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressitem',
            name='categorie',
            field=models.CharField(choices=[('hotellerie', 'Hôtellerie & voyage'), ('design', 'Design & art de vivre'), ('mode', 'Mode & lifestyle'), ('food', 'Gastronomie & boissons'), ('culture', 'Art, culture & patrimoine'), ('habitat', 'Architecture & habitat'), ('beaute', 'Beauté & bien-être'), ('societe', 'Société & tendances'), ('events', 'Salons & événements'), ('autre', 'Autre / à trier')], default='autre', max_length=40),
        ),
    ]
