# Generated by Django 5.2.17 on 2026-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0002_alter_pressitem_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressitem',
            name='draft_chapo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='draft_corps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='draft_genere_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='draft_statut',
            field=models.CharField(choices=[('vide', 'Pas de brouillon'), ('brouillon', 'Brouillon généré'), ('valide', 'Validé'), ('publie', 'Publié')], default='vide', max_length=20),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='draft_titre',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='publier_le',
            field=models.DateField(blank=True, help_text='Date de publication planifiée', null=True),
        ),
    ]
