# Generated by Django 5.2.17 on 2026-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0003_pressitem_draft_chapo_pressitem_draft_corps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image de référence (vignette)', max_length=1000),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text="URLs d'images pour le carrousel"),
        ),
    ]
