# Generated by Django 5.2.17 on 2026-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0004_pressitem_image_url_pressitem_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressitem',
            name='image_alt',
            field=models.CharField(blank=True, help_text="Texte alternatif de l'image de référence", max_length=300),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='images_local',
            field=models.JSONField(blank=True, default=list, help_text='Chemins locaux des images téléchargées (pour export MCP)'),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='liens_internes',
            field=models.JSONField(blank=True, default=list, help_text='Articles liés : [{pk, titre, slug}]'),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (~155 car.)', max_length=320),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Titre optimisé SEO (~60 car.)', max_length=300),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Mots-clés / tags'),
        ),
    ]
