# Generated by Django 5.2.17 on 2026-09-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0005_pressitem_image_alt_pressitem_images_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressitem',
            name='corps_html',
            field=models.TextField(blank=True, help_text='Corps HTML brut conservé (ré-extractible)'),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='liens_sources',
            field=models.JSONField(blank=True, default=list, help_text='Liens trouvés dans le mail : [{url, texte, kind}]'),
        ),
    ]
