# Generated by Django 5.2.17 on 2026-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0006_pressitem_corps_html_pressitem_liens_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressitem',
            name='mcp_article_id',
            field=models.CharField(blank=True, help_text='article_id renvoyé par le MCP après draft_article', max_length=64),
        ),
    ]
