# Generated by Django 5.2.17 on 2026-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0007_pressitem_mcp_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressitem',
            name='cover_url',
            field=models.CharField(blank=True, help_text='Image principale retenue (parmi galerie / proposée)', max_length=1000),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='galerie',
            field=models.JSONField(blank=True, default=list, help_text='Ordre choisi de la galerie (drag-n-drop) ; 1re = après la cover'),
        ),
    ]
