# Generated by Django 5.2.17 on 2026-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0008_pressitem_cover_url_pressitem_galerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressitem',
            name='mcp_pushed_at',
            field=models.DateTimeField(blank=True, help_text='Dernière poussée vers le MCP', null=True),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='mcp_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('draft', 'Brouillon sur le blog'), ('published', 'Publié (validé)')], help_text='État côté blog (rafraîchi via list_drafts)', max_length=20),
        ),
    ]
