# Generated by Django 5.2.17 on 2026-09-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0009_pressitem_mcp_pushed_at_pressitem_mcp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mcp_token',
            field=models.CharField(blank=True, help_text='Token MCP du blog (secret)', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='mcp_url',
            field=models.CharField(blank=True, help_text='Endpoint MCP du blog (vide = 13-Atmosphère)', max_length=300),
        ),
    ]
