# Generated by Django 5.2.17 on 2026-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0010_blog_mcp_token_blog_mcp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bloc',
            field=models.CharField(blank=True, help_text='Regroupement (onglet) éditorial', max_length=80),
        ),
    ]
