# Generated by Django 5.2.17 on 2026-09-26 20:50

import apps.carreaux.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinted', '0013_stockitem_grade_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default=apps.carreaux.models._gen_ref, help_text='Référence courte (uuid4 tronqué)', max_length=40, unique=True)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('sous_total', models.DecimalField(decimal_places=2, help_text='Somme des produits avant remise', max_digits=9)),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remise appliquée (10 % si sous-total ≥ 150 €)', max_digits=9)),
                ('livraison', models.DecimalField(decimal_places=2, default=Decimal('6.70'), help_text='Frais de livraison fixes', max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, help_text='sous_total - remise + livraison', max_digits=9)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('shipped', 'Expédié'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande boutique',
                'verbose_name_plural': 'Commandes boutique',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='BoutiqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text='Prix de vente public (PA × 1.35 recommandé)', max_digits=9)),
                ('image_url', models.URLField(blank=True, help_text='URL Cloudflare Images ou chemin media')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('stock_item', models.OneToOneField(help_text="Article d'entrepôt associé", on_delete=django.db.models.deletion.CASCADE, related_name='boutique_product', to='vinted.stockitem')),
            ],
            options={
                'verbose_name': 'Produit boutique',
                'verbose_name_plural': 'Produits boutique',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BoutiqueOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Snapshot du prix au moment de la commande', max_digits=9)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='carreaux.boutiqueorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='carreaux.boutiqueproduct')),
            ],
            options={
                'verbose_name': 'Ligne de commande boutique',
                'verbose_name_plural': 'Lignes de commande boutique',
                'ordering': ['id'],
            },
        ),
    ]
