# Generated by Django 5.2.17 on 2026-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinted_id', models.CharField(help_text='ID Vinted du feedback', max_length=40, unique=True)),
                ('auteur', models.CharField(max_length=120)),
                ('note', models.PositiveSmallIntegerField(default=5)),
                ('commentaire', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('vinted_url', models.URLField(blank=True, help_text='Lien profil Vinted du vendeur')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avis Vinted',
                'verbose_name_plural': 'Avis Vinted',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
