# Generated by Django 5.2.17 on 2026-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('sms', 'SMS'), ('autre', 'Autre')], default='email', max_length=20)),
                ('ext_id', models.CharField(max_length=500, unique=True)),
                ('expediteur', models.CharField(blank=True, max_length=300)),
                ('sujet', models.CharField(blank=True, max_length=500)),
                ('corps', models.TextField(blank=True)),
                ('recu_le', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.CharField(blank=True, max_length=40)),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=10)),
                ('needs_reply', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('repondu', 'Répondu'), ('archive', 'Archivé')], default='nouveau', max_length=12)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recu_le', '-id'],
                'indexes': [models.Index(fields=['channel', 'statut'], name='comms_messa_channel_3f6d07_idx'), models.Index(fields=['priorite'], name='comms_messa_priorit_dd79aa_idx')],
            },
        ),
    ]
