# Generated by Django 5.2.17 on 2026-09-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='draft_reply',
            field=models.TextField(blank=True, help_text='Réponse suggérée (IA), à valider avant envoi'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
