# Generated by Django 5.2.17 on 2026-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_message_draft_reply_message_reply_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.CharField(blank=True, help_text="Id plateforme de l'expéditeur (wa_id / PSID / IGSID) — pour répondre", max_length=120),
        ),
    ]
