# Generated by Django 5.2.17 on 2026-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('messenger', 'Messenger'), ('sms', 'SMS'), ('autre', 'Autre')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(blank=True, help_text="Id plateforme de l'expéditeur", max_length=120),
        ),
    ]
