"""Catalogue des produits commercialisés — éditer ici pour ajouter/modifier."""

PRODUITS = [
    {
        "slug": "astragso",
        "nom": "AstraGSO",
        "tagline": "Satellite operations simplified",
        "description": "Plateforme de gestion et de suivi d'opérations satellitaires géostationnaires.",
        "url": "https://astragso.com",
        "categorie": "Aerospace",
        "preview_mode": "desktop",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M12 2a10 10 0 0 1 10 10"/><path d="M2 12a10 10 0 0 1 10-10"/><path d="M12 22a10 10 0 0 1-10-10"/><path d="M22 12a10 10 0 0 1-10 10"/></svg>""",
    },
    {
        "slug": "biorl",
        "nom": "biorl",
        "tagline": "Your bio, your store",
        "description": "Lien en bio convertisseur — transforme votre profil en boutique intégrée.",
        "url": "https://o9n.shop",
        "categorie": "E-commerce",
        "preview_mode": "mobile",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/></svg>""",
    },
    {
        "slug": "bodyboard",
        "nom": "BodyBoard",
        "tagline": "Track your body, own your progress",
        "description": "Tableau de bord fitness pour suivre ses performances corporelles et ses objectifs.",
        "url": "https://bodyboard.space",
        "categorie": "Fitness",
        "preview_mode": "mobile",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8h1a4 4 0 0 1 0 8h-1"/><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/><line x1="6" y1="1" x2="6" y2="4"/><line x1="10" y1="1" x2="10" y2="4"/><line x1="14" y1="1" x2="14" y2="4"/></svg>""",
    },
    {
        "slug": "cdcnails",
        "nom": "CDC Nails",
        "tagline": "La beauté, en un clic",
        "description": "Solution de gestion et de réservation en ligne pour les instituts de beauté ongulaire.",
        "url": "https://cdcnails.beauty",
        "categorie": "Beauté",
        "preview_mode": "mobile",
        "couleur": "#e07dbd",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>""",
    },
    {
        "slug": "callflow",
        "nom": "CallFlow",
        "tagline": "Voice flows, automated",
        "description": "Constructeur de flux d'appels automatisés — IVR, routage, scripts, sans code.",
        "url": "https://callflow.services",
        "categorie": "Telecom",
        "preview_mode": "desktop",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.22h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 9.91a16 16 0 0 0 6.11 6.11l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>""",
    },
    {
        "slug": "coachmatch",
        "nom": "CoachMatch",
        "tagline": "Find your perfect coach",
        "description": "Marketplace de mise en relation entre coachs sportifs et clients, avec suivi de programme.",
        "url": "https://coachmatch.fit",
        "categorie": "Fitness",
        "preview_mode": "mobile",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="4"/><path d="M6 20v-2a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v2"/></svg>""",
    },
    {
        "slug": "corpusclip",
        "nom": "CorpusClip",
        "tagline": "Clip, index, search your content",
        "description": "Outil d'extraction et d'indexation de corpus textuels pour la recherche et l'analyse.",
        "url": "https://corpusclip.com",
        "categorie": "Productivité",
        "preview_mode": "desktop",
        "couleur": "#e0c34a",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="2" width="6" height="6" rx="1"/><rect x="9" y="16" width="6" height="6" rx="1"/><rect x="2" y="9" width="6" height="6" rx="1"/><rect x="16" y="9" width="6" height="6" rx="1"/><line x1="15" y1="5" x2="16" y2="5"/><line x1="3" y1="12" x2="9" y2="12"/><line x1="15" y1="12" x2="16" y2="12"/><line x1="12" y1="15" x2="12" y2="16"/></svg>""",
    },
    {
        "slug": "deepdive",
        "nom": "DeepDive",
        "tagline": "AI-powered video intelligence",
        "description": "Analyse vidéo par IA : transcription, résumé, chapitrage et extraction d'insights.",
        "url": "https://vidai.space",
        "categorie": "IA & Vidéo",
        "preview_mode": "desktop",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2"/></svg>""",
    },
    {
        "slug": "dopr",
        "nom": "Dopr",
        "tagline": "Ship faster, deploy smarter",
        "description": "Plateforme de déploiement et de gestion d'environnements pour équipes produit.",
        "url": "https://dopr.app",
        "categorie": "DevOps",
        "preview_mode": "desktop",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>""",
    },
    {
        "slug": "fleetdeck",
        "nom": "FleetDeck",
        "tagline": "Every asset, in real time",
        "description": "Outil de suivi et de supervision de flotte avec chronologie des interventions.",
        "url": "https://chronarch.pro",
        "categorie": "Fleet & Logistique",
        "preview_mode": "desktop",
        "couleur": "#e0c34a",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="3" width="15" height="13" rx="1"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>""",
    },
    {
        "slug": "flumet",
        "nom": "Flumet",
        "tagline": "Control your digital place",
        "description": "Outil de gestion d'espace numérique centralisé pour équipes hybrides.",
        "url": "https://ctrlplace.fr",
        "categorie": "Workplace",
        "preview_mode": "desktop",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>""",
    },
    {
        "slug": "foncierops",
        "nom": "FoncierOps",
        "tagline": "L'immobilier, opérationnel",
        "description": "Logiciel de gestion opérationnelle pour promoteurs et gestionnaires fonciers.",
        "url": "https://foncierops.com",
        "categorie": "Immobilier",
        "preview_mode": "desktop",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M3 22V8l9-6 9 6v14H3z"/><path d="M9 22V12h6v10"/></svg>""",
    },
    {
        "slug": "vocalis",
        "nom": "Vocalis",
        "tagline": "Your voice, your frontier",
        "description": "Plateforme de coaching vocal et de reconnaissance vocale pour créateurs de contenu.",
        "url": "https://vocalis.world",
        "categorie": "Voice & Audio",
        "preview_mode": "mobile",
        "couleur": "#a78bfa",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a3 3 0 0 1 3 3v7a3 3 0 0 1-6 0V5a3 3 0 0 1 3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/></svg>""",
    },
    {
        "slug": "frontiere",
        "nom": "Frontière",
        "tagline": "Push forward",
        "description": "Outil de veille et d'exploration de nouvelles frontières sectorielles pour décideurs.",
        "url": "https://frontforth.xyz",
        "categorie": "Veille & Stratégie",
        "preview_mode": "desktop",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>""",
    },
    {
        "slug": "gentabs",
        "nom": "GenTabs",
        "tagline": "Generate any table, instantly",
        "description": "Générateur de tableaux et de données structurées par IA — export CSV, JSON, Excel.",
        "url": "https://egid.app",
        "categorie": "IA & Productivité",
        "preview_mode": "desktop",
        "couleur": "#e0c34a",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="3" y1="15" x2="21" y2="15"/><line x1="9" y1="3" x2="9" y2="21"/><line x1="15" y1="3" x2="15" y2="21"/></svg>""",
    },
    {
        "slug": "gettestforge",
        "nom": "TestForge",
        "tagline": "Forge your test suite",
        "description": "Plateforme de génération et d'exécution de tests automatisés pour applications web.",
        "url": "https://gettestforge.com",
        "categorie": "DevTools",
        "preview_mode": "desktop",
        "couleur": "#ec5f57",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>""",
    },
    {
        "slug": "katanakungfu",
        "nom": "KatanaKungfu",
        "tagline": "Precision in every move",
        "description": "Application d'entraînement aux arts martiaux avec suivi de progression et vidéos coaching.",
        "url": "https://katanakungfu.fr",
        "categorie": "Sport & Arts Martiaux",
        "preview_mode": "mobile",
        "couleur": "#ec5f57",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="19" x2="19" y2="5"/><path d="M17 5h2v2"/><path d="M5 19H3l4-4"/></svg>""",
    },
    {
        "slug": "kimchi",
        "nom": "Kimchi",
        "tagline": "La boutique qui a du goût",
        "description": "Boutique en ligne spécialisée dans les produits asiatiques authentiques et lifestyle.",
        "url": "https://kimchi.boutique",
        "categorie": "E-commerce",
        "preview_mode": "mobile",
        "couleur": "#e07dbd",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/></svg>""",
    },
    {
        "slug": "kloz",
        "nom": "Kloz",
        "tagline": "Close deals, not browsers",
        "description": "CRM léger orienté closing commercial — pipeline visuel, relances automatiques.",
        "url": "https://kloz.world",
        "categorie": "Sales & CRM",
        "preview_mode": "desktop",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 11 12 14 22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></svg>""",
    },
    {
        "slug": "leadingpoint",
        "nom": "LeadingPoint",
        "tagline": "Lead the score",
        "description": "Plateforme de scoring et de qualification de leads pour équipes commerciales B2B.",
        "url": "https://2157.fr",
        "categorie": "Sales & CRM",
        "preview_mode": "desktop",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>""",
    },
    {
        "slug": "leon",
        "nom": "Leon",
        "tagline": "Reelay your business",
        "description": "Assistant opérationnel pour automatiser les tâches récurrentes des TPE/PME.",
        "url": "https://reelay.biz",
        "categorie": "Automatisation",
        "preview_mode": "desktop",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14M4.93 4.93a10 10 0 0 0 0 14.14"/></svg>""",
    },
    {
        "slug": "mckp",
        "nom": "MCKP",
        "tagline": "Pro tools for serious work",
        "description": "Suite d'outils professionnels pour consultants et freelances exigeants.",
        "url": "https://mckp.pro",
        "categorie": "Productivité",
        "preview_mode": "desktop",
        "couleur": "#a78bfa",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>""",
    },
    {
        "slug": "montblanc",
        "nom": "Montblanc",
        "tagline": "Control from the summit",
        "description": "Interface de pilotage centralisé pour gérer plusieurs espaces de travail numériques.",
        "url": "https://ctrlplace.fr",
        "categorie": "Workplace",
        "preview_mode": "desktop",
        "couleur": "#e0c34a",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><polygon points="3 20 12 4 21 20 3 20"/></svg>""",
    },
    {
        "slug": "nexafoundry",
        "nom": "NexaFoundry",
        "tagline": "Build the next thing",
        "description": "Environnement de prototypage rapide et de forge de produits numériques pour startups.",
        "url": "https://foundry.io",
        "categorie": "DevTools",
        "preview_mode": "desktop",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/></svg>""",
    },
    {
        "slug": "o9n",
        "nom": "o9n",
        "tagline": "One link, one world",
        "description": "Hub de liens et de présence en ligne ultra-léger pour créateurs et marques.",
        "url": "https://o9n.world",
        "categorie": "Social & Links",
        "preview_mode": "mobile",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>""",
    },
    {
        "slug": "pricerhub",
        "nom": "PricerHub",
        "tagline": "FX signals, decoded",
        "description": "Agrégateur de signaux de trading forex avec alertes en temps réel et analyse technique.",
        "url": "https://fxsignal.club",
        "categorie": "Finance & Trading",
        "preview_mode": "desktop",
        "couleur": "#e0c34a",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg>""",
    },
    {
        "slug": "propulse",
        "nom": "Propulse",
        "tagline": "Eyeballs on your brand",
        "description": "Outil de croissance organique et de visibilité — analytics, contenu, audience.",
        "url": "https://eyeball.run",
        "categorie": "Growth & Marketing",
        "preview_mode": "desktop",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12s2.545-5 7-5c4.454 0 7 5 7 5s-2.546 5-7 5c-4.455 0-7-5-7-5z"/><circle cx="12" cy="12" r="2"/></svg>""",
    },
    {
        "slug": "reelay",
        "nom": "Reelay",
        "tagline": "Relay your content",
        "description": "Plateforme de republication et de syndication de contenu multicanal.",
        "url": "https://reelay.fr",
        "categorie": "Content & Media",
        "preview_mode": "desktop",
        "couleur": "#a78bfa",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg>""",
    },
    {
        "slug": "reelay-blog",
        "nom": "Reelay Blog",
        "tagline": "Thoughts worth relaying",
        "description": "Blog et publication éditoriale associés à l'écosystème Reelay.",
        "url": "https://reelay.biz",
        "categorie": "Content & Media",
        "preview_mode": "desktop",
        "couleur": "#a78bfa",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>""",
    },
    {
        "slug": "retardmaxxin",
        "nom": "RetardMaxxin",
        "tagline": "Max out the delay",
        "description": "Outil de gestion de la procrastination productive — batching, délais, priorisation inversée.",
        "url": "https://retardmaxxin.com",
        "categorie": "Productivité",
        "preview_mode": "mobile",
        "couleur": "#ec5f57",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>""",
    },
    {
        "slug": "rimbup",
        "nom": "Rimb'UP",
        "tagline": "Le bot qui gère",
        "description": "Assistant Telegram intelligent pour automatiser votre quotidien et piloter vos projets.",
        "url": "https://rimbup.fr",
        "categorie": "IA & Assistant",
        "preview_mode": "mobile",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>""",
    },
    {
        "slug": "scrollingua",
        "nom": "ScrollingUA",
        "tagline": "Scroll through knowledge",
        "description": "Plateforme de veille et de curation de contenu en format scroll infini thématisé.",
        "url": "https://scrollingua.fr",
        "categorie": "Veille & Média",
        "preview_mode": "mobile",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>""",
    },
    {
        "slug": "signalnest",
        "nom": "SignalNest",
        "tagline": "Trade signals, nested",
        "description": "Gestionnaire de signaux de trading avec alertes multi-stratégies et back-testing.",
        "url": "https://signalnest.trade",
        "categorie": "Finance & Trading",
        "preview_mode": "desktop",
        "couleur": "#e0c34a",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>""",
    },
    {
        "slug": "socialnest",
        "nom": "SocialNest",
        "tagline": "Your social hub",
        "description": "Gestionnaire de réseaux sociaux centralisé — planning, analytics, publication.",
        "url": "https://getsocialnest.com",
        "categorie": "Social & Marketing",
        "preview_mode": "desktop",
        "couleur": "#e07dbd",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></svg>""",
    },
    {
        "slug": "sportpass",
        "nom": "SportPass",
        "tagline": "Your all-access sports pass",
        "description": "Accès groupé à du contenu sport premium : ebooks, programmes, coaching vidéo.",
        "url": "https://sportpass.vip",
        "categorie": "Sport & Contenu",
        "preview_mode": "mobile",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20h20M6 20V10M12 20V4M18 20v-6"/></svg>""",
    },
    {
        "slug": "streakx",
        "nom": "StreakX",
        "tagline": "Keep the streak alive",
        "description": "Application de suivi d'habitudes et de streaks avec gamification et défis sociaux.",
        "url": "https://streakx.xyz",
        "categorie": "Productivité & Bien-être",
        "preview_mode": "mobile",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>""",
    },
    {
        "slug": "titanreliability",
        "nom": "Titan Reliability",
        "tagline": "Industrial-grade reliability",
        "description": "Système de monitoring et de fiabilité pour infrastructures industrielles critiques.",
        "url": "https://titanreliabilitysystem.llc",
        "categorie": "Infrastructure",
        "preview_mode": "desktop",
        "couleur": "#a78bfa",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>""",
    },
    {
        "slug": "treetop",
        "nom": "Treetop",
        "tagline": "Rise above the noise",
        "description": "Vue d'ensemble hiérarchique de vos espaces de travail et projets actifs.",
        "url": "https://ctrlplace.fr",
        "categorie": "Workplace",
        "preview_mode": "desktop",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>""",
    },
    {
        "slug": "upvid",
        "nom": "UpVid",
        "tagline": "Boost your video reach",
        "description": "Plateforme de diffusion et de monétisation vidéo, optimisée pour les créateurs indépendants.",
        "url": "https://upvid.app",
        "categorie": "Media & Vidéo",
        "preview_mode": "desktop",
        "couleur": "#f77615",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3" fill="currentColor" stroke="none"/></svg>""",
    },
    {
        "slug": "piiitch",
        "nom": "Piiitch",
        "tagline": "Pitch like you mean it",
        "description": "Outil de création et d'envoi de pitchs visuels pour startups et entrepreneurs.",
        "url": "https://piiitch.com",
        "categorie": "Startup & Pitch",
        "preview_mode": "desktop",
        "couleur": "#4d8dff",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15V6"/><path d="M18.5 18a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/><path d="M12 12H3"/><path d="M16 6H3"/><path d="M12 18H3"/></svg>""",
    },
    {
        "slug": "viraldm",
        "nom": "ViralDM",
        "tagline": "DMs that convert",
        "description": "Automatisation des messages directs Instagram/Twitter pour des campagnes virales.",
        "url": "https://viraldm.fun",
        "categorie": "Social & Marketing",
        "preview_mode": "mobile",
        "couleur": "#e07dbd",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>""",
    },
    {
        "slug": "walletop",
        "nom": "iWallet",
        "tagline": "Your wallet, smarter",
        "description": "Portefeuille numérique intelligent avec suivi des dépenses et recommandations financières.",
        "url": "https://iwallet.pro",
        "categorie": "Finance & Fintech",
        "preview_mode": "mobile",
        "couleur": "#7ece4e",
        "icone": """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>""",
    },
]
