# Generated by Django 5.2.17 on 2026-08-17 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObserverSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False, verbose_name='mode live')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réglages observateur',
            },
        ),
        migrations.CreateModel(
            name='RedactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, verbose_name='motif')),
                ('replacement', models.CharField(default='•••', max_length=60, verbose_name='remplacement')),
                ('is_regex', models.BooleanField(default=False, verbose_name='expression régulière')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redaction_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'règle de masquage',
                'ordering': ['-created_at'],
            },
        ),
    ]
