# Generated by Django 5.2.17 on 2026-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VintedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=40, unique=True)),
                ('images', models.JSONField(blank=True, default=list, help_text='Chemins des photos reçues')),
                ('reference_image', models.CharField(blank=True, help_text='Photo la plus lisible', max_length=500)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('format_colis', models.CharField(blank=True, help_text='Taille de colis Vinted', max_length=60)),
                ('etat', models.CharField(blank=True, choices=[('neuf_etiquette', 'Neuf avec étiquette'), ('neuf_sans', 'Neuf sans étiquette'), ('tres_bon', 'Très bon état'), ('bon', 'Bon état'), ('satisfaisant', 'Satisfaisant')], max_length=20)),
                ('marque', models.CharField(blank=True, max_length=120)),
                ('categorie', models.CharField(blank=True, max_length=120)),
                ('statut', models.CharField(choices=[('nouveau', 'Photos reçues'), ('genere', 'Titre/description générés'), ('pret', 'Prêt à publier'), ('publie', 'Publié sur Vinted')], default='nouveau', max_length=12)),
                ('vinted_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
