# Generated by Django 5.2.17 on 2026-09-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VintedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, help_text='N° de commande / transaction Vinted (identifiant public)', max_length=60)),
                ('titre', models.CharField(blank=True, help_text="Libellé de l'article (repli si l'annonce manque)", max_length=200)),
                ('acheteur', models.CharField(blank=True, help_text='Pseudo acheteur Vinted (pas de donnée perso)', max_length=120)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, help_text="Coût d'acquisition de la carte", max_digits=9, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente (net vendeur Vinted)', max_digits=9, null=True)),
                ('frais', models.DecimalField(decimal_places=2, default=0, help_text='Frais vendeur (port à charge, mise en avant, gradation…)', max_digits=9)),
                ('statut_envoi', models.CharField(choices=[('a_preparer', 'À préparer'), ('etiquette', 'Étiquette éditée'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('cloture', 'Clôturé'), ('probleme', 'Problème / litige')], db_index=True, default='a_preparer', max_length=12)),
                ('transporteur', models.CharField(blank=True, help_text='Chronopost, Mondial Relay, Colissimo…', max_length=60)),
                ('tracking', models.CharField(blank=True, help_text='N° de suivi', max_length=80)),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('date_expedition', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, help_text="Annonce d'origine (si connue)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='vinted.vintedlisting')),
            ],
            options={
                'verbose_name': 'Commande Vinted',
                'verbose_name_plural': 'Commandes Vinted',
                'ordering': ['-date_vente', '-id'],
            },
        ),
    ]
