# Generated by Django 5.2.17 on 2026-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0002_vintedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintedorder',
            name='plateforme',
            field=models.CharField(choices=[('vinted', 'Vinted'), ('cardmarket', 'CardMarket'), ('ebay', 'eBay')], db_index=True, default='vinted', help_text='Place de marché de la vente', max_length=12),
        ),
        migrations.AlterField(
            model_name='vintedorder',
            name='numero',
            field=models.CharField(blank=True, db_index=True, help_text='N° de commande / transaction (identifiant public de la plateforme)', max_length=60),
        ),
    ]
