# Generated by Django 5.2.17 on 2026-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0003_vintedorder_plateforme_alter_vintedorder_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vintedorder',
            name='tracking',
            field=models.CharField(blank=True, help_text='N° de suivi / ticket de référence', max_length=80),
        ),
        migrations.AlterField(
            model_name='vintedorder',
            name='transporteur',
            field=models.CharField(blank=True, choices=[('mondial_relay', 'Mondial Relay'), ('colissimo', 'Colissimo'), ('chronopost', 'Chronopost'), ('shop2shop', 'Chronopost Shop2Shop'), ('relais_colis', 'Relais Colis'), ('vinted_go', 'Vinted Go'), ('lettre_suivie', 'Lettre suivie (La Poste)'), ('ups', 'UPS'), ('dpd', 'DPD'), ('gls', 'GLS'), ('dhl', 'DHL'), ('autre', 'Autre')], help_text='Mondial Relay, Colissimo, Chronopost…', max_length=60),
        ),
    ]
