# Generated by Django 5.2.17 on 2026-09-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0004_alter_vintedorder_tracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, help_text='N°/set/ref carte', max_length=120)),
                ('source', models.CharField(choices=[('tiktok', 'TikTok'), ('import_pokepoke', 'Vinted — import_pokepoke'), ('live', 'Live'), ('vinted', 'Vinted'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, help_text="Coût unitaire d'acquisition", max_digits=9, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('destin', models.CharField(choices=[('a_definir', 'À définir'), ('vente_directe', 'Vendre à réception'), ('grade_collectaura', 'Grader — Collect Aura (Boulogne-Billancourt, express)'), ('grade_ccc', 'Grader — CCC (Malakoff, express)'), ('garder', 'Garder / collection')], default='a_definir', help_text='Devenir prévu à réception', max_length=20)),
                ('statut', models.CharField(choices=[('en_transit', 'En transit'), ('recu', 'Reçu'), ('a_grader', 'À grader'), ('en_gradation', 'En gradation'), ('grade', 'Gradé'), ('a_lister', 'À lister'), ('liste', 'Listé sur Vinted'), ('vendu', 'Vendu')], db_index=True, default='en_transit', max_length=14)),
                ('gradeur', models.CharField(blank=True, help_text='Ex. Collect Aura (BB) / CCC (Malakoff)', max_length=120)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article en stock (entrepôt)',
                'verbose_name_plural': 'Entrepôt (stock)',
                'ordering': ['-id'],
            },
        ),
    ]
