# Generated by Django 5.2.17 on 2026-09-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0005_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('canal', models.CharField(blank=True, help_text='Vinted, TikTok, live, site… (où on achète)', max_length=60)),
                ('contact', models.CharField(blank=True, help_text='Pseudo, URL, contact', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='source',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('import_pokepoke', 'Vinted — import_pokepoke'), ('live', 'Live'), ('vinted', 'Vinted'), ('autre', 'Autre')], default='autre', help_text="Canal d'achat", max_length=20),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='vinted.fournisseur'),
        ),
    ]
