# Generated by Django 5.2.17 on 2026-09-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0006_fournisseur_alter_stockitem_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintedorder',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text="Source d'approvisionnement de l'article", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='vinted.fournisseur'),
        ),
    ]
