# Generated by Django 5.2.17 on 2026-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0007_vintedorder_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintedorder',
            name='stock_items',
            field=models.ManyToManyField(blank=True, help_text="Article(s) d'entrepôt vendus dans cette commande", related_name='commandes', to='vinted.stockitem'),
        ),
        migrations.AlterField(
            model_name='vintedorder',
            name='plateforme',
            field=models.CharField(choices=[('vinted', 'Vinted'), ('cardmarket', 'CardMarket'), ('ebay', 'eBay'), ('direct', 'Vente directe')], db_index=True, default='vinted', help_text='Place de marché de la vente', max_length=12),
        ),
    ]
