# Generated by Django 5.2.17 on 2026-09-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0008_vintedorder_stock_items_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='listing',
            field=models.OneToOneField(blank=True, help_text='Annonce Vinted associée à cet article (remplie à la publication)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_item', to='vinted.vintedlisting'),
        ),
    ]
