# Generated by Django 5.2.17 on 2026-09-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0009_stockitem_listing_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintedorder',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Remise accordée à l'acheteur (lot/bundle — déduite du prix nominal)", max_digits=9),
        ),
    ]
