# Generated by Django 5.2.17 on 2026-09-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0010_remise_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, help_text='Libellé affiché (auto depuis stock_item.nom à la création)', max_length=200)),
                ('prix_vente_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente par unité (avant remise globale du lot)', max_digits=9, null=True)),
                ('prix_achat_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text="Coût d'acquisition par unité", max_digits=9, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Commande parente', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='vinted.vintedorder')),
                ('stock_item', models.OneToOneField(blank=True, help_text='Article physique correspondant (optionnel pour lignes libres)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne', to='vinted.stockitem')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['id'],
            },
        ),
    ]
