# Generated by Django 5.2.17 on 2026-09-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0012_stockitem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='grade_note',
            field=models.CharField(blank=True, help_text='Note attribuée par le gradeur (ex. 9, 9.5, 10)', max_length=20),
        ),
    ]
