# Generated by Django 5.2.17 on 2026-10-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0013_stockitem_grade_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='prix_affiche',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente affiché (live / stand)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='prix_repli_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de repli 1 — live show (plancher acceptable)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='prix_repli_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de repli 2 — live show (plancher absolu)', max_digits=9, null=True),
        ),
    ]
