# Generated by Django 5.2.17 on 2026-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0014_add_stock_live_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='image_recto',
            field=models.ImageField(blank=True, help_text='Photo recto de la carte (intake card show)', null=True, upload_to='stock/recto/'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='image_verso',
            field=models.ImageField(blank=True, help_text='Photo verso de la carte (intake card show)', null=True, upload_to='stock/verso/'),
        ),
    ]
