# Generated by Django 5.2.17 on 2026-08-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0006_workspace_max_panes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name='objectif')),
                ('status', models.CharField(choices=[('draft', 'brouillon'), ('running', 'en cours'), ('paused', 'en pause'), ('done', 'terminée'), ('failed', 'échouée')], default='draft', max_length=10)),
                ('mode', models.CharField(choices=[('manual', 'validation humaine'), ('auto', 'automatique')], default='manual', max_length=10)),
                ('max_parallel', models.PositiveSmallIntegerField(default=3, verbose_name='agents simultanés')),
                ('budget_usd', models.DecimalField(blank=True, decimal_places=2, help_text="Plafond dur : le dispatch s'arrête au-delà. Vide = pas de plafond.", max_digits=8, null=True, verbose_name='budget')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=12, verbose_name='clé')),
                ('title', models.CharField(max_length=200)),
                ('brief', models.TextField(blank=True, help_text="Ce qui sera envoyé à l'agent.", verbose_name='consigne')),
                ('status', models.CharField(choices=[('todo', 'à faire'), ('ready', 'prête'), ('running', 'en cours'), ('review', 'à relire'), ('done', 'terminée'), ('failed', 'échouée'), ('blocked', 'bloquée')], default='todo', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=2)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='blocks', to='tasker.task')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasker.mission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=20)),
                ('pane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspaces.pane')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasker.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('mission', 'key'), name='uniq_task_key_per_mission'),
        ),
    ]
