# Generated by Django 5.2.17 on 2026-08-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
        ('workspaces', '0007_pane_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='planner_pane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_missions', to='workspaces.headlesspane'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('draft', 'brouillon'), ('planning', 'planification'), ('running', 'en cours'), ('paused', 'en pause'), ('done', 'terminée'), ('failed', 'échouée')], default='draft', max_length=10),
        ),
    ]
