# Generated by Django 5.2.17 on 2026-08-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_mission_planner_pane_alter_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='task_class',
            field=models.CharField(choices=[('draft', 'Draft / rédaction courte'), ('summarize', 'Résumé'), ('glue', 'Glue code / scripts'), ('route', 'Routage de messages'), ('code_small', 'Code borné'), ('code_heavy', 'Code lourd / refacto'), ('architecture', 'Architecture / conception'), ('long_context', 'Très long contexte'), ('default', 'Défaut')], default='default', max_length=32, verbose_name='classe de tâche'),
        ),
    ]
