# Generated by Django 5.2.17 on 2026-09-19 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('codeur', 'Codeur.com'), ('manuel', 'Manuel'), ('autre', 'Autre')], default='codeur', max_length=20)),
                ('ext_url', models.URLField(max_length=600, unique=True)),
                ('titre', models.CharField(max_length=400)),
                ('budget_texte', models.CharField(blank=True, max_length=120)),
                ('budget_eur', models.PositiveIntegerField(default=0, help_text='Budget estimé en € (parsé)')),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, max_length=120)),
                ('competences', models.JSONField(blank=True, default=list)),
                ('publie_le', models.CharField(blank=True, max_length=80)),
                ('deadline_jours', models.CharField(blank=True, max_length=40)),
                ('vues', models.CharField(blank=True, max_length=40)),
                ('offres_existantes', models.CharField(blank=True, max_length=40)),
                ('client_nom', models.CharField(blank=True, max_length=200)),
                ('client_societe', models.CharField(blank=True, max_length=200)),
                ('client_localisation', models.CharField(blank=True, max_length=200)),
                ('client_site', models.CharField(blank=True, max_length=300)),
                ('client_url', models.CharField(blank=True, max_length=600)),
                ('contact_tel', models.CharField(blank=True, max_length=60)),
                ('contact_email', models.CharField(blank=True, max_length=200)),
                ('email_verifie', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('nouveau', 'Nouveau'), ('qualifie', 'Qualifié'), ('contacte', 'Contacté'), ('proposition', 'Proposition'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='nouveau', max_length=16)),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('prochaine_action', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-budget_eur', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('ancien_stage', models.CharField(blank=True, max_length=16)),
                ('nouveau_stage', models.CharField(blank=True, max_length=16)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='prospection.opportunity')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='prospection_stage_c8d2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['categorie'], name='prospection_categor_4b065e_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['priorite'], name='prospection_priorit_a6c0b2_idx'),
        ),
    ]
