# Generated by Django 5.2.17 on 2026-09-19 10:13

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-score', '-budget_eur', '-id']},
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='deadline_jours',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='prochaine_action',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='codeur_id',
            field=models.CharField(blank=True, db_index=True, help_text='guid RSS / id projet — clé de dédup', max_length=32),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='compte_multi',
            field=models.BooleanField(default=False, help_text='Client multi-annonces'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_detection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_offre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_relance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='etat',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('ferme', 'Fermé')], default='ouvert', max_length=12),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='motif_perte',
            field=models.CharField(blank=True, choices=[('', '—'), ('prix', 'Prix'), ('delai', 'Délai'), ('concurrent', 'Concurrent retenu'), ('injoignable', 'Client injoignable'), ('abandon', 'Projet abandonné')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='motif_rejet',
            field=models.CharField(blank=True, choices=[('', '—'), ('hors_fit', 'Hors fit technique'), ('budget', 'Budget insuffisant'), ('trop_offres', "Trop d'offres"), ('remontee', 'Annonce remontée'), ('etat', 'État non ouvert'), ('brief', 'Brief inexploitable'), ('doublon', 'Doublon')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offres_detection',
            field=models.PositiveIntegerField(blank=True, help_text="Nb d'offres relevé à la détection", null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='publie_le_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='resume_besoin',
            field=models.CharField(blank=True, help_text='2 lignes reformulées', max_length=400),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Score 0-100 (priorisation)'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tjm',
            field=models.BooleanField(default=False, help_text='Mission en régie (tarif/jour) plutôt que forfait'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ancien_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='nouveau_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='competences',
            field=models.JSONField(blank=True, default=list, help_text='Profils recherchés'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('detecte', 'Détecté'), ('qualifie', 'Qualifié'), ('offre_envoyee', 'Offre envoyée'), ('echange', 'Échange'), ('gagne', 'Gagné'), ('perdu', 'Perdu'), ('sans_reponse', 'Sans réponse'), ('opportunite_future', 'Opportunité future'), ('rejete', 'Rejeté')], default='detecte', max_length=20),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['etat'], name='prospection_etat_489569_idx'),
        ),
    ]
