# Generated by Django 5.2.17 on 2026-09-19 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0002_alter_opportunity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('qualification', 'Qualification'), ('offre', "Envoyer l'offre"), ('relance', 'Relance'), ('echange', 'Échange client'), ('cloture', 'Clôture'), ('autre', 'Autre')], default='autre', max_length=16)),
                ('libelle', models.CharField(max_length=300)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('fait', models.BooleanField(default=False)),
                ('fait_le', models.DateTimeField(blank=True, null=True)),
                ('auto', models.BooleanField(default=False, help_text="Créée par l'agent (IA/SLA)")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='prospection.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_vente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fait', 'echeance', 'id'],
            },
        ),
    ]
