# Generated by Django 5.2.17 on 2026-09-26 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0003_salesstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offre', 'Offre initiale'), ('relance_j2', 'Relance J+2'), ('relance_j5', 'Relance J+5 (dossier)'), ('relance_j10', 'Relance J+10 (RDV)'), ('relance_j20', 'Clôture J+20')], default='offre', max_length=16)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('approuve', 'Approuvé'), ('envoye', 'Envoyé'), ('rejete', 'Rejeté')], default='brouillon', max_length=12)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('note_interne', models.CharField(blank=True, max_length=300)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='prospection.opportunity')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
