# Generated by Django 5.2.17 on 2026-08-17 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(blank=True, max_length=60, verbose_name='label')),
                ('status', models.CharField(choices=[('idle', 'prêt'), ('running', 'en cours'), ('dead', 'terminé')], default='idle', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeadlessPane',
            fields=[
                ('pane_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workspaces.pane')),
                ('prompt_initial', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'pane chat',
            },
            bases=('workspaces.pane',),
        ),
        migrations.CreateModel(
            name='PtyPane',
            fields=[
                ('pane_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workspaces.pane')),
                ('cmd', models.CharField(default='claude', help_text='Binaire (liste blanche COCKPIT_ALLOWED_CMDS) + arguments.', max_length=200, verbose_name='commande')),
                ('cwd', models.CharField(blank=True, help_text='Vide = répertoire du workspace.', max_length=500, verbose_name='répertoire')),
            ],
            options={
                'verbose_name': 'pane terminal',
            },
            bases=('workspaces.pane',),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('slug', models.SlugField(max_length=100)),
                ('cwd', models.CharField(default='~', help_text='Répertoire par défaut des panes de ce workspace.', max_length=500, verbose_name='répertoire de travail')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pane',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panes', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_workspace_slug_per_owner'),
        ),
    ]
