# Generated by Django 5.2.17 on 2026-08-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pane',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='visible en live'),
        ),
        migrations.AddField(
            model_name='pane',
            name='public_alias',
            field=models.CharField(blank=True, max_length=60, verbose_name='alias public'),
        ),
    ]
