# Generated by Django 5.2.17 on 2026-08-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_pane_is_public_pane_public_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pane',
            name='runtime_boot_id',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
