# Generated by Django 5.2.17 on 2026-08-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_pane_runtime_boot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pane',
            name='resume_pending',
            field=models.BooleanField(default=False),
        ),
    ]
