# Generated by Django 5.2.17 on 2026-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_pane_resume_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlesspane',
            name='claude_session_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
