# Generated by Django 5.2.17 on 2026-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_headlesspane_claude_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='max_panes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Vide = plafond global. Nombre d'instances qui peuvent tourner en même temps ici.", null=True, verbose_name='agents simultanés'),
        ),
    ]
