# Generated by Django 5.2.17 on 2026-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspace_max_panes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pane',
            name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
