# Generated by Django 5.2.17 on 2026-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_pane_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlesspane',
            name='model_id',
            field=models.CharField(choices=[('claude-haiku-4-5-20251001', 'Haiku 4.5'), ('claude-sonnet-4-5', 'Sonnet 4.5'), ('claude-sonnet-4-6', 'Sonnet 4.6'), ('claude-opus-4-6', 'Opus 4.6'), ('claude-opus-4-8', 'Opus 4.8'), ('gpt-oss-20b', 'OSS Local')], default='claude-sonnet-4-6', max_length=100, verbose_name='modèle'),
        ),
    ]
