# Generated by Django 5.2.17 on 2026-08-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(verbose_name='consigne')),
                ('tag', models.CharField(choices=[('security', 'sécurité'), ('growth', 'croissance'), ('workflow', 'workflow'), ('memory', 'mémoire'), ('knowledge', 'connaissance'), ('deploy', 'déploiement')], default='workflow', max_length=16)),
                ('is_builtin', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_builtin', 'order', 'name'],
            },
        ),
    ]
