# Generated by Django 5.2.17 on 2026-09-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinted', '0003_vintedorder_plateforme_alter_vintedorder_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('ebay', 'eBay'), ('cardmarket', 'CardMarket')], db_index=True, max_length=12)),
                ('listing_type', models.CharField(choices=[('fixed', 'Prix fixe (vente directe)'), ('auction', 'Enchères')], default='fixed', max_length=8)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('etat', models.CharField(blank=True, choices=[('mint', 'Neuf / Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Bon'), ('played', 'Joué')], max_length=12)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, help_text='Prix fixe, ou mise de départ pour une enchère', max_digits=9, null=True)),
                ('prix_reserve', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de réserve (enchères eBay)', max_digits=9, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('duree_jours', models.PositiveIntegerField(blank=True, help_text='Durée (enchères / GTC eBay)', null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('catalog_id', models.CharField(blank=True, help_text='ID produit catalogue (CardMarket)', max_length=80)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('erreur', 'Erreur'), ('vendu', 'Vendu'), ('cloture', 'Clôturé')], db_index=True, default='brouillon', max_length=12)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True, help_text='Dernier message / erreur API')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('source_listing', models.ForeignKey(blank=True, help_text='Carte source (annonce Vinted assistée)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_listings', to='vinted.vintedlisting')),
            ],
            options={
                'verbose_name': 'Mise en vente (place de marché)',
                'verbose_name_plural': 'Mises en vente (places de marché)',
                'ordering': ['-id'],
            },
        ),
    ]
