# Generated by Django 5.2.17 on 2026-08-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_pane_is_public_pane_public_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('origin', models.CharField(default='raw', max_length=10)),
                ('event_type', models.CharField(max_length=30)),
                ('payload', models.JSONField()),
                ('normalized', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspaces.pane')),
            ],
            options={
                'ordering': ['pane_id', 'seq'],
                'indexes': [models.Index(fields=['pane', 'seq'], name='chat_eventl_pane_id_dde344_idx')],
                'constraints': [models.UniqueConstraint(fields=('pane', 'seq'), name='uniq_event_seq_per_pane')],
            },
        ),
    ]
